-- Reset and insert ~60 English-named products with enhanced details and unique images
USE [shopgiay]
GO

-- Cleanup existing product-related data (safe if tables are empty)
IF OBJECT_ID(N'dbo.ProductImages', N'U') IS NOT NULL DELETE FROM dbo.ProductImages;
IF OBJECT_ID(N'dbo.ProductFeatures', N'U') IS NOT NULL DELETE FROM dbo.ProductFeatures;
IF OBJECT_ID(N'dbo.ProductSizes', N'U') IS NOT NULL DELETE FROM dbo.ProductSizes;
IF OBJECT_ID(N'dbo.ProductTags', N'U') IS NOT NULL DELETE FROM dbo.ProductTags;
IF OBJECT_ID(N'dbo.ProductColors', N'U') IS NOT NULL DELETE FROM dbo.ProductColors;
IF OBJECT_ID(N'dbo.Products', N'U') IS NOT NULL DELETE FROM dbo.Products;
IF OBJECT_ID(N'dbo.Products', N'U') IS NOT NULL DBCC CHECKIDENT ('dbo.Products', RESEED, 0);

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Air Zoom Pegasus 40', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 2877499, 3194024, 10, N'Nike Air Zoom Pegasus 40 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Moisture-wicking lining keeps feet dry and Flexible design for natural foot movement. The Nike Air Zoom Pegasus 40 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/nike-air-zoom-pegasus-40-main.jpg', N'["/images/products/nike-air-zoom-pegasus-40-main.jpg","/images/products/nike-air-zoom-pegasus-40-side.jpg","/images/products/nike-air-zoom-pegasus-40-back.jpg","/images/products/nike-air-zoom-pegasus-40-sole.jpg"]', N'["/images/products/nike-air-zoom-pegasus-40-main.jpg","/images/products/nike-air-zoom-pegasus-40-side.jpg","/images/products/nike-air-zoom-pegasus-40-back.jpg","/images/products/nike-air-zoom-pegasus-40-sole.jpg"]', 4.7, 111, 1, 107, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Air Force 1', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 2635522, 3057206, 14, N'Nike Air Force 1 represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Classic silhouette with modern updates and Flexible design for natural foot movement. The Nike Air Force 1 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/nike-air-force-1-main.jpg', N'["/images/products/nike-air-force-1-main.jpg","/images/products/nike-air-force-1-side.jpg","/images/products/nike-air-force-1-back.jpg","/images/products/nike-air-force-1-sole.jpg"]', N'["/images/products/nike-air-force-1-main.jpg","/images/products/nike-air-force-1-side.jpg","/images/products/nike-air-force-1-back.jpg","/images/products/nike-air-force-1-sole.jpg"]', 4.7, 186, 1, 28, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Air Max 270', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2536437, 2916903, 13, N'Nike Air Max 270 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Classic silhouette with modern updates and Breathable mesh upper for optimal ventilation. The Nike Air Max 270 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Easy to style with any casual outfit and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/nike-air-max-270-main.jpg', N'["/images/products/nike-air-max-270-main.jpg","/images/products/nike-air-max-270-side.jpg","/images/products/nike-air-max-270-back.jpg","/images/products/nike-air-max-270-sole.jpg"]', N'["/images/products/nike-air-max-270-main.jpg","/images/products/nike-air-max-270-side.jpg","/images/products/nike-air-max-270-back.jpg","/images/products/nike-air-max-270-sole.jpg"]', 4.9, 42, 1, 75, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Air Max 90', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 1056485, 1183263, 11, N'Nike Air Max 90 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Breathable mesh upper for optimal ventilation and Cushioned midsole for superior comfort. The Nike Air Max 90 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/nike-air-max-90-main.jpg', N'["/images/products/nike-air-max-90-main.jpg","/images/products/nike-air-max-90-side.jpg","/images/products/nike-air-max-90-back.jpg","/images/products/nike-air-max-90-sole.jpg"]', N'["/images/products/nike-air-max-90-main.jpg","/images/products/nike-air-max-90-side.jpg","/images/products/nike-air-max-90-back.jpg","/images/products/nike-air-max-90-sole.jpg"]', 4.7, 112, 1, 51, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike React Infinity Run 3', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 952526, 1152556, 17, N'Nike React Infinity Run 3 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Durable rubber outsole with excellent traction and Removable foam insole for custom fit. The Nike React Infinity Run 3 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Comfortable for extended wear periods and Suitable for both indoor and outdoor use, you''ll experience unmatched comfort and style.', N'/images/products/nike-react-infinity-run-3-main.jpg', N'["/images/products/nike-react-infinity-run-3-main.jpg","/images/products/nike-react-infinity-run-3-side.jpg","/images/products/nike-react-infinity-run-3-back.jpg","/images/products/nike-react-infinity-run-3-sole.jpg"]', N'["/images/products/nike-react-infinity-run-3-main.jpg","/images/products/nike-react-infinity-run-3-side.jpg","/images/products/nike-react-infinity-run-3-back.jpg","/images/products/nike-react-infinity-run-3-sole.jpg"]', 4.8, 193, 1, 79, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike ZoomX Vaporfly Next% 2', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 2450276, 2964834, 17, N'Nike ZoomX Vaporfly Next% 2 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Breathable mesh upper for optimal ventilation and Cushioned midsole for superior comfort. The Nike ZoomX Vaporfly Next% 2 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/nike-zoomx-vaporfly-next-2-main.jpg', N'["/images/products/nike-zoomx-vaporfly-next-2-main.jpg","/images/products/nike-zoomx-vaporfly-next-2-side.jpg","/images/products/nike-zoomx-vaporfly-next-2-back.jpg","/images/products/nike-zoomx-vaporfly-next-2-sole.jpg"]', N'["/images/products/nike-zoomx-vaporfly-next-2-main.jpg","/images/products/nike-zoomx-vaporfly-next-2-side.jpg","/images/products/nike-zoomx-vaporfly-next-2-back.jpg","/images/products/nike-zoomx-vaporfly-next-2-sole.jpg"]', 4.5, 109, 1, 84, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Dunk Low', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Basketball'), 1036137, 1150112, 10, N'Nike Dunk Low represents the perfect fusion of style, comfort, and performance. Designed for basketball activities, this shoe features Cushioned midsole for superior comfort and Lightweight construction for all-day wear. The Nike Dunk Low is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/nike-dunk-low-main.jpg', N'["/images/products/nike-dunk-low-main.jpg","/images/products/nike-dunk-low-side.jpg","/images/products/nike-dunk-low-back.jpg","/images/products/nike-dunk-low-sole.jpg"]', N'["/images/products/nike-dunk-low-main.jpg","/images/products/nike-dunk-low-side.jpg","/images/products/nike-dunk-low-back.jpg","/images/products/nike-dunk-low-sole.jpg"]', 4.8, 188, 1, 112, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Blazer Mid ''77', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 2353306, 2918099, 19, N'Nike Blazer Mid ''77 represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Cushioned midsole for superior comfort and Removable foam insole for custom fit. The Nike Blazer Mid ''77 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Comfortable for extended wear periods and Easy to style with any casual outfit, you''ll experience unmatched comfort and style.', N'/images/products/nike-blazer-mid-77-main.jpg', N'["/images/products/nike-blazer-mid-77-main.jpg","/images/products/nike-blazer-mid-77-side.jpg","/images/products/nike-blazer-mid-77-back.jpg","/images/products/nike-blazer-mid-77-sole.jpg"]', N'["/images/products/nike-blazer-mid-77-main.jpg","/images/products/nike-blazer-mid-77-side.jpg","/images/products/nike-blazer-mid-77-back.jpg","/images/products/nike-blazer-mid-77-sole.jpg"]', 4.2, 179, 1, 25, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Pegasus Trail 4', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 1580406, 1801663, 12, N'Nike Pegasus Trail 4 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Lightweight construction for all-day wear and Padded collar and tongue for ankle support. The Nike Pegasus Trail 4 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/nike-pegasus-trail-4-main.jpg', N'["/images/products/nike-pegasus-trail-4-main.jpg","/images/products/nike-pegasus-trail-4-side.jpg","/images/products/nike-pegasus-trail-4-back.jpg","/images/products/nike-pegasus-trail-4-sole.jpg"]', N'["/images/products/nike-pegasus-trail-4-main.jpg","/images/products/nike-pegasus-trail-4-side.jpg","/images/products/nike-pegasus-trail-4-back.jpg","/images/products/nike-pegasus-trail-4-sole.jpg"]', 4.5, 34, 1, 51, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Air Huarache', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 2377177, 2733754, 13, N'Nike Air Huarache represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Removable foam insole for custom fit. The Nike Air Huarache is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/nike-air-huarache-main.jpg', N'["/images/products/nike-air-huarache-main.jpg","/images/products/nike-air-huarache-side.jpg","/images/products/nike-air-huarache-back.jpg","/images/products/nike-air-huarache-sole.jpg"]', N'["/images/products/nike-air-huarache-main.jpg","/images/products/nike-air-huarache-side.jpg","/images/products/nike-air-huarache-back.jpg","/images/products/nike-air-huarache-sole.jpg"]', 4.9, 18, 1, 75, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Revolution 6', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2062865, 2392923, 14, N'Nike Revolution 6 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Reinforced toe cap for durability and Removable foam insole for custom fit. The Nike Revolution 6 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Comfortable for extended wear periods and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/nike-revolution-6-main.jpg', N'["/images/products/nike-revolution-6-main.jpg","/images/products/nike-revolution-6-side.jpg","/images/products/nike-revolution-6-back.jpg","/images/products/nike-revolution-6-sole.jpg"]', N'["/images/products/nike-revolution-6-main.jpg","/images/products/nike-revolution-6-side.jpg","/images/products/nike-revolution-6-back.jpg","/images/products/nike-revolution-6-sole.jpg"]', 4, 118, 1, 53, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Nike Metcon 9', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Nike'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 3082261, 3667891, 16, N'Nike Metcon 9 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Breathable mesh upper for optimal ventilation and Flexible design for natural foot movement. The Nike Metcon 9 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/nike-metcon-9-main.jpg', N'["/images/products/nike-metcon-9-main.jpg","/images/products/nike-metcon-9-side.jpg","/images/products/nike-metcon-9-back.jpg","/images/products/nike-metcon-9-sole.jpg"]', N'["/images/products/nike-metcon-9-main.jpg","/images/products/nike-metcon-9-side.jpg","/images/products/nike-metcon-9-back.jpg","/images/products/nike-metcon-9-sole.jpg"]', 4.7, 98, 1, 61, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Ultraboost Light', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 1488809, 1771683, 16, N'Adidas Ultraboost Light represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Durable rubber outsole with excellent traction and Classic silhouette with modern updates. The Adidas Ultraboost Light is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/adidas-ultraboost-light-main.jpg', N'["/images/products/adidas-ultraboost-light-main.jpg","/images/products/adidas-ultraboost-light-side.jpg","/images/products/adidas-ultraboost-light-back.jpg","/images/products/adidas-ultraboost-light-sole.jpg"]', N'["/images/products/adidas-ultraboost-light-main.jpg","/images/products/adidas-ultraboost-light-side.jpg","/images/products/adidas-ultraboost-light-back.jpg","/images/products/adidas-ultraboost-light-sole.jpg"]', 4.7, 49, 1, 39, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas NMD R1', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 917511, 1045963, 12, N'Adidas NMD R1 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Durable rubber outsole with excellent traction and Lightweight construction for all-day wear. The Adidas NMD R1 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/adidas-nmd-r1-main.jpg', N'["/images/products/adidas-nmd-r1-main.jpg","/images/products/adidas-nmd-r1-side.jpg","/images/products/adidas-nmd-r1-back.jpg","/images/products/adidas-nmd-r1-sole.jpg"]', N'["/images/products/adidas-nmd-r1-main.jpg","/images/products/adidas-nmd-r1-side.jpg","/images/products/adidas-nmd-r1-back.jpg","/images/products/adidas-nmd-r1-sole.jpg"]', 4.6, 171, 1, 86, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Stan Smith', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 875083, 1050100, 17, N'Adidas Stan Smith represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Durable rubber outsole with excellent traction and Flexible design for natural foot movement. The Adidas Stan Smith is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/adidas-stan-smith-main.jpg', N'["/images/products/adidas-stan-smith-main.jpg","/images/products/adidas-stan-smith-side.jpg","/images/products/adidas-stan-smith-back.jpg","/images/products/adidas-stan-smith-sole.jpg"]', N'["/images/products/adidas-stan-smith-main.jpg","/images/products/adidas-stan-smith-side.jpg","/images/products/adidas-stan-smith-back.jpg","/images/products/adidas-stan-smith-sole.jpg"]', 4.7, 151, 1, 40, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Superstar', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1090470, 1232231, 12, N'Adidas Superstar represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Durable rubber outsole with excellent traction. The Adidas Superstar is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Suitable for both indoor and outdoor use, you''ll experience unmatched comfort and style.', N'/images/products/adidas-superstar-main.jpg', N'["/images/products/adidas-superstar-main.jpg","/images/products/adidas-superstar-side.jpg","/images/products/adidas-superstar-back.jpg","/images/products/adidas-superstar-sole.jpg"]', N'["/images/products/adidas-superstar-main.jpg","/images/products/adidas-superstar-side.jpg","/images/products/adidas-superstar-back.jpg","/images/products/adidas-superstar-sole.jpg"]', 4, 81, 1, 75, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Adizero Adios 8', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 2517538, 2995870, 16, N'Adidas Adizero Adios 8 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Breathable mesh upper for optimal ventilation and Cushioned midsole for superior comfort. The Adidas Adizero Adios 8 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/adidas-adizero-adios-8-main.jpg', N'["/images/products/adidas-adizero-adios-8-main.jpg","/images/products/adidas-adizero-adios-8-side.jpg","/images/products/adidas-adizero-adios-8-back.jpg","/images/products/adidas-adizero-adios-8-sole.jpg"]', N'["/images/products/adidas-adizero-adios-8-main.jpg","/images/products/adidas-adizero-adios-8-side.jpg","/images/products/adidas-adizero-adios-8-back.jpg","/images/products/adidas-adizero-adios-8-sole.jpg"]', 4.1, 94, 1, 48, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Solarboost 5', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 2991819, 3380755, 12, N'Adidas Solarboost 5 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Padded collar and tongue for ankle support and Classic silhouette with modern updates. The Adidas Solarboost 5 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Easy to style with any casual outfit, you''ll experience unmatched comfort and style.', N'/images/products/adidas-solarboost-5-main.jpg', N'["/images/products/adidas-solarboost-5-main.jpg","/images/products/adidas-solarboost-5-side.jpg","/images/products/adidas-solarboost-5-back.jpg","/images/products/adidas-solarboost-5-sole.jpg"]', N'["/images/products/adidas-solarboost-5-main.jpg","/images/products/adidas-solarboost-5-side.jpg","/images/products/adidas-solarboost-5-back.jpg","/images/products/adidas-solarboost-5-sole.jpg"]', 4.9, 126, 1, 104, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Samba OG', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 3459494, 4220583, 18, N'Adidas Samba OG represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Breathable mesh upper for optimal ventilation. The Adidas Samba OG is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/adidas-samba-og-main.jpg', N'["/images/products/adidas-samba-og-main.jpg","/images/products/adidas-samba-og-side.jpg","/images/products/adidas-samba-og-back.jpg","/images/products/adidas-samba-og-sole.jpg"]', N'["/images/products/adidas-samba-og-main.jpg","/images/products/adidas-samba-og-side.jpg","/images/products/adidas-samba-og-back.jpg","/images/products/adidas-samba-og-sole.jpg"]', 4.5, 195, 1, 118, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Gazelle', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 3380630, 3718693, 9, N'Adidas Gazelle represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Removable foam insole for custom fit and Padded collar and tongue for ankle support. The Adidas Gazelle is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Comfortable for extended wear periods and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/adidas-gazelle-main.jpg', N'["/images/products/adidas-gazelle-main.jpg","/images/products/adidas-gazelle-side.jpg","/images/products/adidas-gazelle-back.jpg","/images/products/adidas-gazelle-sole.jpg"]', N'["/images/products/adidas-gazelle-main.jpg","/images/products/adidas-gazelle-side.jpg","/images/products/adidas-gazelle-back.jpg","/images/products/adidas-gazelle-sole.jpg"]', 4.6, 130, 1, 44, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Terrex Swift R3', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2264778, 2763029, 18, N'Adidas Terrex Swift R3 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Breathable mesh upper for optimal ventilation and Cushioned midsole for superior comfort. The Adidas Terrex Swift R3 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/adidas-terrex-swift-r3-main.jpg', N'["/images/products/adidas-terrex-swift-r3-main.jpg","/images/products/adidas-terrex-swift-r3-side.jpg","/images/products/adidas-terrex-swift-r3-back.jpg","/images/products/adidas-terrex-swift-r3-sole.jpg"]', N'["/images/products/adidas-terrex-swift-r3-main.jpg","/images/products/adidas-terrex-swift-r3-side.jpg","/images/products/adidas-terrex-swift-r3-back.jpg","/images/products/adidas-terrex-swift-r3-sole.jpg"]', 4.7, 172, 1, 60, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Forum Low', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Basketball'), 951623, 1180013, 19, N'Adidas Forum Low represents the perfect fusion of style, comfort, and performance. Designed for basketball activities, this shoe features Flexible design for natural foot movement and Moisture-wicking lining keeps feet dry. The Adidas Forum Low is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Durable construction for long-lasting use, you''ll experience unmatched comfort and style.', N'/images/products/adidas-forum-low-main.jpg', N'["/images/products/adidas-forum-low-main.jpg","/images/products/adidas-forum-low-side.jpg","/images/products/adidas-forum-low-back.jpg","/images/products/adidas-forum-low-sole.jpg"]', N'["/images/products/adidas-forum-low-main.jpg","/images/products/adidas-forum-low-side.jpg","/images/products/adidas-forum-low-back.jpg","/images/products/adidas-forum-low-sole.jpg"]', 4.3, 31, 1, 85, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Duramo SL', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 1680359, 2100449, 20, N'Adidas Duramo SL represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Moisture-wicking lining keeps feet dry and Breathable mesh upper for optimal ventilation. The Adidas Duramo SL is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Ideal for light workouts and training and Easy to style with any casual outfit, you''ll experience unmatched comfort and style.', N'/images/products/adidas-duramo-sl-main.jpg', N'["/images/products/adidas-duramo-sl-main.jpg","/images/products/adidas-duramo-sl-side.jpg","/images/products/adidas-duramo-sl-back.jpg","/images/products/adidas-duramo-sl-sole.jpg"]', N'["/images/products/adidas-duramo-sl-main.jpg","/images/products/adidas-duramo-sl-side.jpg","/images/products/adidas-duramo-sl-back.jpg","/images/products/adidas-duramo-sl-sole.jpg"]', 4.9, 55, 1, 65, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Adidas Runfalcon 3', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Adidas'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 2174335, 2456999, 12, N'Adidas Runfalcon 3 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Flexible design for natural foot movement and Removable foam insole for custom fit. The Adidas Runfalcon 3 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/adidas-runfalcon-3-main.jpg', N'["/images/products/adidas-runfalcon-3-main.jpg","/images/products/adidas-runfalcon-3-side.jpg","/images/products/adidas-runfalcon-3-back.jpg","/images/products/adidas-runfalcon-3-sole.jpg"]', N'["/images/products/adidas-runfalcon-3-main.jpg","/images/products/adidas-runfalcon-3-side.jpg","/images/products/adidas-runfalcon-3-back.jpg","/images/products/adidas-runfalcon-3-sole.jpg"]', 4.2, 126, 1, 55, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Chuck Taylor All Star', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1905310, 2172053, 12, N'Converse Chuck Taylor All Star represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Durable rubber outsole with excellent traction. The Converse Chuck Taylor All Star is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Easy to style with any casual outfit, you''ll experience unmatched comfort and style.', N'/images/products/converse-chuck-taylor-all-star-main.jpg', N'["/images/products/converse-chuck-taylor-all-star-main.jpg","/images/products/converse-chuck-taylor-all-star-side.jpg","/images/products/converse-chuck-taylor-all-star-back.jpg","/images/products/converse-chuck-taylor-all-star-sole.jpg"]', N'["/images/products/converse-chuck-taylor-all-star-main.jpg","/images/products/converse-chuck-taylor-all-star-side.jpg","/images/products/converse-chuck-taylor-all-star-back.jpg","/images/products/converse-chuck-taylor-all-star-sole.jpg"]', 4.1, 135, 1, 27, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Chuck 70', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1261508, 1463349, 14, N'Converse Chuck 70 represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Padded collar and tongue for ankle support. The Converse Chuck 70 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/converse-chuck-70-main.jpg', N'["/images/products/converse-chuck-70-main.jpg","/images/products/converse-chuck-70-side.jpg","/images/products/converse-chuck-70-back.jpg","/images/products/converse-chuck-70-sole.jpg"]', N'["/images/products/converse-chuck-70-main.jpg","/images/products/converse-chuck-70-side.jpg","/images/products/converse-chuck-70-back.jpg","/images/products/converse-chuck-70-sole.jpg"]', 4.2, 168, 1, 97, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse One Star Pro', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Skateboarding'), 2724156, 3405195, 20, N'Converse One Star Pro represents the perfect fusion of style, comfort, and performance. Designed for skateboarding activities, this shoe features Durable rubber outsole with excellent traction and Lightweight construction for all-day wear. The Converse One Star Pro is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/converse-one-star-pro-main.jpg', N'["/images/products/converse-one-star-pro-main.jpg","/images/products/converse-one-star-pro-side.jpg","/images/products/converse-one-star-pro-back.jpg","/images/products/converse-one-star-pro-sole.jpg"]', N'["/images/products/converse-one-star-pro-main.jpg","/images/products/converse-one-star-pro-side.jpg","/images/products/converse-one-star-pro-back.jpg","/images/products/converse-one-star-pro-sole.jpg"]', 4.5, 50, 1, 44, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Run Star Hike', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2760526, 3036579, 9, N'Converse Run Star Hike represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Moisture-wicking lining keeps feet dry and Lightweight construction for all-day wear. The Converse Run Star Hike is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/converse-run-star-hike-main.jpg', N'["/images/products/converse-run-star-hike-main.jpg","/images/products/converse-run-star-hike-side.jpg","/images/products/converse-run-star-hike-back.jpg","/images/products/converse-run-star-hike-sole.jpg"]', N'["/images/products/converse-run-star-hike-main.jpg","/images/products/converse-run-star-hike-side.jpg","/images/products/converse-run-star-hike-back.jpg","/images/products/converse-run-star-hike-sole.jpg"]', 4.7, 22, 1, 30, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse CONS Fastbreak Pro', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Skateboarding'), 1259621, 1498949, 16, N'Converse CONS Fastbreak Pro represents the perfect fusion of style, comfort, and performance. Designed for skateboarding activities, this shoe features Breathable mesh upper for optimal ventilation and Lightweight construction for all-day wear. The Converse CONS Fastbreak Pro is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Easy to style with any casual outfit and Suitable for both indoor and outdoor use, you''ll experience unmatched comfort and style.', N'/images/products/converse-cons-fastbreak-pro-main.jpg', N'["/images/products/converse-cons-fastbreak-pro-main.jpg","/images/products/converse-cons-fastbreak-pro-side.jpg","/images/products/converse-cons-fastbreak-pro-back.jpg","/images/products/converse-cons-fastbreak-pro-sole.jpg"]', N'["/images/products/converse-cons-fastbreak-pro-main.jpg","/images/products/converse-cons-fastbreak-pro-side.jpg","/images/products/converse-cons-fastbreak-pro-back.jpg","/images/products/converse-cons-fastbreak-pro-sole.jpg"]', 4.3, 171, 1, 28, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Pro Leather', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Skateboarding'), 1375767, 1664678, 17, N'Converse Pro Leather represents the perfect fusion of style, comfort, and performance. Designed for skateboarding activities, this shoe features Moisture-wicking lining keeps feet dry and Durable rubber outsole with excellent traction. The Converse Pro Leather is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/converse-pro-leather-main.jpg', N'["/images/products/converse-pro-leather-main.jpg","/images/products/converse-pro-leather-side.jpg","/images/products/converse-pro-leather-back.jpg","/images/products/converse-pro-leather-sole.jpg"]', N'["/images/products/converse-pro-leather-main.jpg","/images/products/converse-pro-leather-side.jpg","/images/products/converse-pro-leather-back.jpg","/images/products/converse-pro-leather-sole.jpg"]', 4.6, 152, 1, 51, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse CX Explore', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 3268848, 3693798, 12, N'Converse CX Explore represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Cushioned midsole for superior comfort and Lightweight construction for all-day wear. The Converse CX Explore is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Easy to style with any casual outfit, you''ll experience unmatched comfort and style.', N'/images/products/converse-cx-explore-main.jpg', N'["/images/products/converse-cx-explore-main.jpg","/images/products/converse-cx-explore-side.jpg","/images/products/converse-cx-explore-back.jpg","/images/products/converse-cx-explore-sole.jpg"]', N'["/images/products/converse-cx-explore-main.jpg","/images/products/converse-cx-explore-side.jpg","/images/products/converse-cx-explore-back.jpg","/images/products/converse-cx-explore-sole.jpg"]', 4.6, 106, 1, 41, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse All Star Move', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 1823552, 2042378, 11, N'Converse All Star Move represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Classic silhouette with modern updates and Breathable mesh upper for optimal ventilation. The Converse All Star Move is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/converse-all-star-move-main.jpg', N'["/images/products/converse-all-star-move-main.jpg","/images/products/converse-all-star-move-side.jpg","/images/products/converse-all-star-move-back.jpg","/images/products/converse-all-star-move-sole.jpg"]', N'["/images/products/converse-all-star-move-main.jpg","/images/products/converse-all-star-move-side.jpg","/images/products/converse-all-star-move-back.jpg","/images/products/converse-all-star-move-sole.jpg"]', 4.2, 123, 1, 65, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Star Player 76', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 3079265, 3602740, 15, N'Converse Star Player 76 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Breathable mesh upper for optimal ventilation and Flexible design for natural foot movement. The Converse Star Player 76 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Easy to style with any casual outfit and Suitable for both indoor and outdoor use, you''ll experience unmatched comfort and style.', N'/images/products/converse-star-player-76-main.jpg', N'["/images/products/converse-star-player-76-main.jpg","/images/products/converse-star-player-76-side.jpg","/images/products/converse-star-player-76-back.jpg","/images/products/converse-star-player-76-sole.jpg"]', N'["/images/products/converse-star-player-76-main.jpg","/images/products/converse-star-player-76-side.jpg","/images/products/converse-star-player-76-back.jpg","/images/products/converse-star-player-76-sole.jpg"]', 4.4, 119, 1, 32, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Weapon CX', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Basketball'), 1049999, 1280999, 18, N'Converse Weapon CX represents the perfect fusion of style, comfort, and performance. Designed for basketball activities, this shoe features Breathable mesh upper for optimal ventilation and Moisture-wicking lining keeps feet dry. The Converse Weapon CX is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Easy to style with any casual outfit, you''ll experience unmatched comfort and style.', N'/images/products/converse-weapon-cx-main.jpg', N'["/images/products/converse-weapon-cx-main.jpg","/images/products/converse-weapon-cx-side.jpg","/images/products/converse-weapon-cx-back.jpg","/images/products/converse-weapon-cx-sole.jpg"]', N'["/images/products/converse-weapon-cx-main.jpg","/images/products/converse-weapon-cx-side.jpg","/images/products/converse-weapon-cx-back.jpg","/images/products/converse-weapon-cx-sole.jpg"]', 4.7, 137, 1, 57, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Lugged 2.0', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2839797, 3549746, 20, N'Converse Lugged 2.0 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Lightweight construction for all-day wear and Flexible design for natural foot movement. The Converse Lugged 2.0 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/converse-lugged-2-0-main.jpg', N'["/images/products/converse-lugged-2-0-main.jpg","/images/products/converse-lugged-2-0-side.jpg","/images/products/converse-lugged-2-0-back.jpg","/images/products/converse-lugged-2-0-sole.jpg"]', N'["/images/products/converse-lugged-2-0-main.jpg","/images/products/converse-lugged-2-0-side.jpg","/images/products/converse-lugged-2-0-back.jpg","/images/products/converse-lugged-2-0-sole.jpg"]', 4, 149, 1, 25, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Converse Jack Purcell', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Converse'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2433226, 2725213, 11, N'Converse Jack Purcell represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Padded collar and tongue for ankle support and Removable foam insole for custom fit. The Converse Jack Purcell is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/converse-jack-purcell-main.jpg', N'["/images/products/converse-jack-purcell-main.jpg","/images/products/converse-jack-purcell-side.jpg","/images/products/converse-jack-purcell-back.jpg","/images/products/converse-jack-purcell-sole.jpg"]', N'["/images/products/converse-jack-purcell-main.jpg","/images/products/converse-jack-purcell-side.jpg","/images/products/converse-jack-purcell-back.jpg","/images/products/converse-jack-purcell-sole.jpg"]', 4.4, 80, 1, 92, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Old Skool', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1698446, 1902260, 11, N'Vans Old Skool represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Reinforced toe cap for durability and Breathable mesh upper for optimal ventilation. The Vans Old Skool is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/vans-old-skool-main.jpg', N'["/images/products/vans-old-skool-main.jpg","/images/products/vans-old-skool-side.jpg","/images/products/vans-old-skool-back.jpg","/images/products/vans-old-skool-sole.jpg"]', N'["/images/products/vans-old-skool-main.jpg","/images/products/vans-old-skool-side.jpg","/images/products/vans-old-skool-back.jpg","/images/products/vans-old-skool-sole.jpg"]', 4.3, 135, 1, 55, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Sk8-Hi', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2814759, 3321416, 15, N'Vans Sk8-Hi represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Moisture-wicking lining keeps feet dry and Breathable mesh upper for optimal ventilation. The Vans Sk8-Hi is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/vans-sk8-hi-main.jpg', N'["/images/products/vans-sk8-hi-main.jpg","/images/products/vans-sk8-hi-side.jpg","/images/products/vans-sk8-hi-back.jpg","/images/products/vans-sk8-hi-sole.jpg"]', N'["/images/products/vans-sk8-hi-main.jpg","/images/products/vans-sk8-hi-side.jpg","/images/products/vans-sk8-hi-back.jpg","/images/products/vans-sk8-hi-sole.jpg"]', 4.1, 162, 1, 86, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Authentic', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 3262909, 4046007, 19, N'Vans Authentic represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Removable foam insole for custom fit and Breathable mesh upper for optimal ventilation. The Vans Authentic is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/vans-authentic-main.jpg', N'["/images/products/vans-authentic-main.jpg","/images/products/vans-authentic-side.jpg","/images/products/vans-authentic-back.jpg","/images/products/vans-authentic-sole.jpg"]', N'["/images/products/vans-authentic-main.jpg","/images/products/vans-authentic-side.jpg","/images/products/vans-authentic-back.jpg","/images/products/vans-authentic-sole.jpg"]', 4.3, 144, 1, 56, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Era', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 2230641, 2587544, 14, N'Vans Era represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Classic silhouette with modern updates and Padded collar and tongue for ankle support. The Vans Era is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Comfortable for extended wear periods and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/vans-era-main.jpg', N'["/images/products/vans-era-main.jpg","/images/products/vans-era-side.jpg","/images/products/vans-era-back.jpg","/images/products/vans-era-sole.jpg"]', N'["/images/products/vans-era-main.jpg","/images/products/vans-era-side.jpg","/images/products/vans-era-back.jpg","/images/products/vans-era-sole.jpg"]', 4.5, 156, 1, 93, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Classic Slip-On', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1424856, 1781070, 20, N'Vans Classic Slip-On represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Moisture-wicking lining keeps feet dry. The Vans Classic Slip-On is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Great for walking and light running and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/vans-classic-slip-on-main.jpg', N'["/images/products/vans-classic-slip-on-main.jpg","/images/products/vans-classic-slip-on-side.jpg","/images/products/vans-classic-slip-on-back.jpg","/images/products/vans-classic-slip-on-sole.jpg"]', N'["/images/products/vans-classic-slip-on-main.jpg","/images/products/vans-classic-slip-on-side.jpg","/images/products/vans-classic-slip-on-back.jpg","/images/products/vans-classic-slip-on-sole.jpg"]', 4.5, 193, 1, 83, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans UltraRange EXO', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 1578448, 1783646, 12, N'Vans UltraRange EXO represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Removable foam insole for custom fit and Padded collar and tongue for ankle support. The Vans UltraRange EXO is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/vans-ultrarange-exo-main.jpg', N'["/images/products/vans-ultrarange-exo-main.jpg","/images/products/vans-ultrarange-exo-side.jpg","/images/products/vans-ultrarange-exo-back.jpg","/images/products/vans-ultrarange-exo-sole.jpg"]', N'["/images/products/vans-ultrarange-exo-main.jpg","/images/products/vans-ultrarange-exo-side.jpg","/images/products/vans-ultrarange-exo-back.jpg","/images/products/vans-ultrarange-exo-sole.jpg"]', 4.4, 99, 1, 117, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans EVDNT UltimateWaffle', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2749071, 3436339, 20, N'Vans EVDNT UltimateWaffle represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Flexible design for natural foot movement and Durable rubber outsole with excellent traction. The Vans EVDNT UltimateWaffle is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/vans-evdnt-ultimatewaffle-main.jpg', N'["/images/products/vans-evdnt-ultimatewaffle-main.jpg","/images/products/vans-evdnt-ultimatewaffle-side.jpg","/images/products/vans-evdnt-ultimatewaffle-back.jpg","/images/products/vans-evdnt-ultimatewaffle-sole.jpg"]', N'["/images/products/vans-evdnt-ultimatewaffle-main.jpg","/images/products/vans-evdnt-ultimatewaffle-side.jpg","/images/products/vans-evdnt-ultimatewaffle-back.jpg","/images/products/vans-evdnt-ultimatewaffle-sole.jpg"]', 4.6, 113, 1, 48, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Ward', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 2824462, 3417599, 17, N'Vans Ward represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Reinforced toe cap for durability. The Vans Ward is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/vans-ward-main.jpg', N'["/images/products/vans-ward-main.jpg","/images/products/vans-ward-side.jpg","/images/products/vans-ward-back.jpg","/images/products/vans-ward-sole.jpg"]', N'["/images/products/vans-ward-main.jpg","/images/products/vans-ward-side.jpg","/images/products/vans-ward-back.jpg","/images/products/vans-ward-sole.jpg"]', 4.6, 53, 1, 104, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Chukka Low', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2415509, 2657060, 9, N'Vans Chukka Low represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Lightweight construction for all-day wear and Breathable mesh upper for optimal ventilation. The Vans Chukka Low is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Perfect for daily wear and casual outings and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/vans-chukka-low-main.jpg', N'["/images/products/vans-chukka-low-main.jpg","/images/products/vans-chukka-low-side.jpg","/images/products/vans-chukka-low-back.jpg","/images/products/vans-chukka-low-sole.jpg"]', N'["/images/products/vans-chukka-low-main.jpg","/images/products/vans-chukka-low-side.jpg","/images/products/vans-chukka-low-back.jpg","/images/products/vans-chukka-low-sole.jpg"]', 4, 102, 1, 115, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Knu Skool', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 3273814, 4059529, 19, N'Vans Knu Skool represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Lightweight construction for all-day wear and Removable foam insole for custom fit. The Vans Knu Skool is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Durable construction for long-lasting use, you''ll experience unmatched comfort and style.', N'/images/products/vans-knu-skool-main.jpg', N'["/images/products/vans-knu-skool-main.jpg","/images/products/vans-knu-skool-side.jpg","/images/products/vans-knu-skool-back.jpg","/images/products/vans-knu-skool-sole.jpg"]', N'["/images/products/vans-knu-skool-main.jpg","/images/products/vans-knu-skool-side.jpg","/images/products/vans-knu-skool-back.jpg","/images/products/vans-knu-skool-sole.jpg"]', 4.1, 110, 1, 120, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Skate Half Cab ''92', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Skateboarding'), 2799052, 3274891, 15, N'Vans Skate Half Cab ''92 represents the perfect fusion of style, comfort, and performance. Designed for skateboarding activities, this shoe features Breathable mesh upper for optimal ventilation and Reinforced toe cap for durability. The Vans Skate Half Cab ''92 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Easy to style with any casual outfit and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/vans-skate-half-cab-92-main.jpg', N'["/images/products/vans-skate-half-cab-92-main.jpg","/images/products/vans-skate-half-cab-92-side.jpg","/images/products/vans-skate-half-cab-92-back.jpg","/images/products/vans-skate-half-cab-92-sole.jpg"]', N'["/images/products/vans-skate-half-cab-92-main.jpg","/images/products/vans-skate-half-cab-92-side.jpg","/images/products/vans-skate-half-cab-92-back.jpg","/images/products/vans-skate-half-cab-92-sole.jpg"]', 4.4, 121, 1, 75, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'Vans Sentry WC', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'Vans'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 1381473, 1713027, 19, N'Vans Sentry WC represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Durable rubber outsole with excellent traction and Removable foam insole for custom fit. The Vans Sentry WC is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Great for walking and light running and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/vans-sentry-wc-main.jpg', N'["/images/products/vans-sentry-wc-main.jpg","/images/products/vans-sentry-wc-side.jpg","/images/products/vans-sentry-wc-back.jpg","/images/products/vans-sentry-wc-sole.jpg"]', N'["/images/products/vans-sentry-wc-main.jpg","/images/products/vans-sentry-wc-side.jpg","/images/products/vans-sentry-wc-back.jpg","/images/products/vans-sentry-wc-sole.jpg"]', 4.3, 169, 1, 63, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 574', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1272614, 1476232, 14, N'New Balance 574 represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Reinforced toe cap for durability. The New Balance 574 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-574-main.jpg', N'["/images/products/new-balance-574-main.jpg","/images/products/new-balance-574-side.jpg","/images/products/new-balance-574-back.jpg","/images/products/new-balance-574-sole.jpg"]', N'["/images/products/new-balance-574-main.jpg","/images/products/new-balance-574-side.jpg","/images/products/new-balance-574-back.jpg","/images/products/new-balance-574-sole.jpg"]', 4.5, 133, 1, 68, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 327', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 2900610, 3596756, 19, N'New Balance 327 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Flexible design for natural foot movement and Breathable mesh upper for optimal ventilation. The New Balance 327 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-327-main.jpg', N'["/images/products/new-balance-327-main.jpg","/images/products/new-balance-327-side.jpg","/images/products/new-balance-327-back.jpg","/images/products/new-balance-327-sole.jpg"]', N'["/images/products/new-balance-327-main.jpg","/images/products/new-balance-327-side.jpg","/images/products/new-balance-327-back.jpg","/images/products/new-balance-327-sole.jpg"]', 4.8, 120, 1, 54, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 550', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Basketball'), 1892162, 2119221, 11, N'New Balance 550 represents the perfect fusion of style, comfort, and performance. Designed for basketball activities, this shoe features Reinforced toe cap for durability and Removable foam insole for custom fit. The New Balance 550 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Easy to style with any casual outfit and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-550-main.jpg', N'["/images/products/new-balance-550-main.jpg","/images/products/new-balance-550-side.jpg","/images/products/new-balance-550-back.jpg","/images/products/new-balance-550-sole.jpg"]', N'["/images/products/new-balance-550-main.jpg","/images/products/new-balance-550-side.jpg","/images/products/new-balance-550-back.jpg","/images/products/new-balance-550-sole.jpg"]', 4.7, 15, 1, 73, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 990v5', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Lifestyle'), 1557237, 1868684, 17, N'New Balance 990v5 represents the perfect fusion of style, comfort, and performance. Designed for lifestyle activities, this shoe features Lightweight construction for all-day wear and Flexible design for natural foot movement. The New Balance 990v5 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-990v5-main.jpg', N'["/images/products/new-balance-990v5-main.jpg","/images/products/new-balance-990v5-side.jpg","/images/products/new-balance-990v5-back.jpg","/images/products/new-balance-990v5-sole.jpg"]', N'["/images/products/new-balance-990v5-main.jpg","/images/products/new-balance-990v5-side.jpg","/images/products/new-balance-990v5-back.jpg","/images/products/new-balance-990v5-sole.jpg"]', 4.2, 116, 1, 116, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 1080v12 Fresh Foam', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 2281219, 2532153, 10, N'New Balance 1080v12 Fresh Foam represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Breathable mesh upper for optimal ventilation and Reinforced toe cap for durability. The New Balance 1080v12 Fresh Foam is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Great for walking and light running and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-1080v12-fresh-foam-main.jpg', N'["/images/products/new-balance-1080v12-fresh-foam-main.jpg","/images/products/new-balance-1080v12-fresh-foam-side.jpg","/images/products/new-balance-1080v12-fresh-foam-back.jpg","/images/products/new-balance-1080v12-fresh-foam-sole.jpg"]', N'["/images/products/new-balance-1080v12-fresh-foam-main.jpg","/images/products/new-balance-1080v12-fresh-foam-side.jpg","/images/products/new-balance-1080v12-fresh-foam-back.jpg","/images/products/new-balance-1080v12-fresh-foam-sole.jpg"]', 4, 70, 1, 92, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 680v7', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 3349184, 3885053, 14, N'New Balance 680v7 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Lightweight construction for all-day wear and Classic silhouette with modern updates. The New Balance 680v7 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-680v7-main.jpg', N'["/images/products/new-balance-680v7-main.jpg","/images/products/new-balance-680v7-side.jpg","/images/products/new-balance-680v7-back.jpg","/images/products/new-balance-680v7-sole.jpg"]', N'["/images/products/new-balance-680v7-main.jpg","/images/products/new-balance-680v7-side.jpg","/images/products/new-balance-680v7-back.jpg","/images/products/new-balance-680v7-sole.jpg"]', 4.3, 151, 1, 27, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 530', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 2188436, 2582354, 15, N'New Balance 530 represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Removable foam insole for custom fit. The New Balance 530 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Great for walking and light running and Ideal for light workouts and training, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-530-main.jpg', N'["/images/products/new-balance-530-main.jpg","/images/products/new-balance-530-side.jpg","/images/products/new-balance-530-back.jpg","/images/products/new-balance-530-sole.jpg"]', N'["/images/products/new-balance-530-main.jpg","/images/products/new-balance-530-side.jpg","/images/products/new-balance-530-back.jpg","/images/products/new-balance-530-sole.jpg"]', 4.7, 85, 1, 79, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 9060', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1431811, 1603628, 11, N'New Balance 9060 represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Lightweight construction for all-day wear and Removable foam insole for custom fit. The New Balance 9060 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Great for walking and light running and Perfect for daily wear and casual outings, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-9060-main.jpg', N'["/images/products/new-balance-9060-main.jpg","/images/products/new-balance-9060-side.jpg","/images/products/new-balance-9060-back.jpg","/images/products/new-balance-9060-sole.jpg"]', N'["/images/products/new-balance-9060-main.jpg","/images/products/new-balance-9060-side.jpg","/images/products/new-balance-9060-back.jpg","/images/products/new-balance-9060-sole.jpg"]', 4.3, 112, 1, 117, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance FuelCell Rebel v3', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 1584406, 1885443, 16, N'New Balance FuelCell Rebel v3 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Classic silhouette with modern updates and Breathable mesh upper for optimal ventilation. The New Balance FuelCell Rebel v3 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Durable construction for long-lasting use, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-fuelcell-rebel-v3-main.jpg', N'["/images/products/new-balance-fuelcell-rebel-v3-main.jpg","/images/products/new-balance-fuelcell-rebel-v3-side.jpg","/images/products/new-balance-fuelcell-rebel-v3-back.jpg","/images/products/new-balance-fuelcell-rebel-v3-sole.jpg"]', N'["/images/products/new-balance-fuelcell-rebel-v3-main.jpg","/images/products/new-balance-fuelcell-rebel-v3-side.jpg","/images/products/new-balance-fuelcell-rebel-v3-back.jpg","/images/products/new-balance-fuelcell-rebel-v3-sole.jpg"]', 4.4, 113, 1, 70, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance Fresh Foam Hierro v7', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Running'), 1713831, 2056597, 17, N'New Balance Fresh Foam Hierro v7 represents the perfect fusion of style, comfort, and performance. Designed for running activities, this shoe features Classic silhouette with modern updates and Lightweight construction for all-day wear. The New Balance Fresh Foam Hierro v7 is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Suitable for both indoor and outdoor use and Versatile design for multiple activities, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-fresh-foam-hierro-v7-main.jpg', N'["/images/products/new-balance-fresh-foam-hierro-v7-main.jpg","/images/products/new-balance-fresh-foam-hierro-v7-side.jpg","/images/products/new-balance-fresh-foam-hierro-v7-back.jpg","/images/products/new-balance-fresh-foam-hierro-v7-sole.jpg"]', N'["/images/products/new-balance-fresh-foam-hierro-v7-main.jpg","/images/products/new-balance-fresh-foam-hierro-v7-side.jpg","/images/products/new-balance-fresh-foam-hierro-v7-back.jpg","/images/products/new-balance-fresh-foam-hierro-v7-sole.jpg"]', 4.8, 64, 1, 32, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 2002R', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 2202906, 2489284, 12, N'New Balance 2002R represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Flexible design for natural foot movement and Reinforced toe cap for durability. The New Balance 2002R is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Durable construction for long-lasting use and Comfortable for extended wear periods, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-2002r-main.jpg', N'["/images/products/new-balance-2002r-main.jpg","/images/products/new-balance-2002r-side.jpg","/images/products/new-balance-2002r-back.jpg","/images/products/new-balance-2002r-sole.jpg"]', N'["/images/products/new-balance-2002r-main.jpg","/images/products/new-balance-2002r-side.jpg","/images/products/new-balance-2002r-back.jpg","/images/products/new-balance-2002r-sole.jpg"]', 4.3, 116, 1, 120, GETDATE(), GETDATE());

INSERT INTO [dbo].[Products] ([Name],[BrandID],[CategoryID],[Price],[OriginalPrice],[Discount],[Description],[MainImage],[ThumbnailImages],[DetailImages],[Rating],[Reviews],[InStock],[StockQuantity],[CreatedAt],[UpdatedAt])
VALUES (N'New Balance 1906R', (SELECT [BrandID] FROM [dbo].[Brands] WHERE [Name] = N'New Balance'), (SELECT [CategoryID] FROM [dbo].[Categories] WHERE [Name] = N'Casual'), 1655472, 2003121, 17, N'New Balance 1906R represents the perfect fusion of style, comfort, and performance. Designed for casual activities, this shoe features Removable foam insole for custom fit and Breathable mesh upper for optimal ventilation. The New Balance 1906R is built to last with premium materials and expert craftsmanship. Whether you''re hitting the streets or heading to the gym, this versatile footwear delivers on all fronts. With its Versatile design for multiple activities and Great for walking and light running, you''ll experience unmatched comfort and style.', N'/images/products/new-balance-1906r-main.jpg', N'["/images/products/new-balance-1906r-main.jpg","/images/products/new-balance-1906r-side.jpg","/images/products/new-balance-1906r-back.jpg","/images/products/new-balance-1906r-sole.jpg"]', N'["/images/products/new-balance-1906r-main.jpg","/images/products/new-balance-1906r-side.jpg","/images/products/new-balance-1906r-back.jpg","/images/products/new-balance-1906r-sole.jpg"]', 4.7, 36, 1, 51, GETDATE(), GETDATE());

-- Done